"""empty message

Revision ID: b44f5d26f550
Revises: a09dec9c8acf
Create Date: 2023-09-10 16:20:31.759888

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b44f5d26f550'
down_revision = 'a09dec9c8acf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.alter_column('f_time',
               existing_type=mysql.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.alter_column('f_time',
               existing_type=mysql.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
