"""empty message

Revision ID: f7590f31d97b
Revises: b44f5d26f550
Create Date: 2023-09-10 16:23:55.705106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7590f31d97b'
down_revision = 'b44f5d26f550'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_index('u_username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.create_index('u_username', ['u_username'], unique=False)

    # ### end Alembic commands ###
