"""empty message

Revision ID: bbd33239773e
Revises: 
Create Date: 2023-09-08 15:40:02.798167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbd33239773e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_captcha',
    sa.Column('u_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('u_email', sa.String(length=100), nullable=False),
    sa.Column('u_captcha', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('u_id')
    )
    op.create_table('illness',
    sa.Column('i_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('i_name', sa.String(length=45), nullable=False),
    sa.Column('i_count', sa.Integer(), nullable=False),
    sa.Column('i_good_fb', sa.Integer(), nullable=False),
    sa.Column('i_bad_fb', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('i_id'),
    sa.UniqueConstraint('i_name')
    )
    op.create_table('user',
    sa.Column('u_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('u_username', sa.String(length=45), nullable=False),
    sa.Column('u_password', sa.String(length=255), nullable=False),
    sa.Column('u_email', sa.String(length=100), nullable=False),
    sa.Column('u_gender', sa.Integer(), nullable=True),
    sa.Column('u_permission', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('u_id'),
    sa.UniqueConstraint('u_email'),
    sa.UniqueConstraint('u_username')
    )
    op.create_table('feedback',
    sa.Column('f_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('f_type', sa.String(length=50), nullable=False),
    sa.Column('f_content', sa.String(length=500), nullable=True),
    sa.Column('f_result', sa.Integer(), nullable=True),
    sa.Column('u_id', sa.Integer(), nullable=False),
    sa.Column('u_username', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['u_id'], ['user.u_id'], ),
    sa.PrimaryKeyConstraint('f_id'),
    sa.UniqueConstraint('u_username')
    )
    op.create_table('user_history',
    sa.Column('h_chatID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('h_question', sa.String(length=255), nullable=False),
    sa.Column('h_answer', sa.String(length=500), nullable=False),
    sa.Column('h_dialogID', sa.Integer(), nullable=False),
    sa.Column('h_time', sa.DateTime(), nullable=False),
    sa.Column('u_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['u_id'], ['user.u_id'], ),
    sa.PrimaryKeyConstraint('h_chatID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_history')
    op.drop_table('feedback')
    op.drop_table('user')
    op.drop_table('illness')
    op.drop_table('email_captcha')
    # ### end Alembic commands ###
